baseURL: "/"
languageCode: "pt"
DefaultContentLanguage: "pt-br"
title: "William Amorim"
theme: KeepIt
paginate: 12
enableEmoji: yes
enableRobotsTXT: yes
publishdir: "docs"
googleAnalytics: ''
disqusShortname: yourdiscussshortname
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
blackfriday:
  hrefTargetBlank: yes
  nofollowLinks: yes
  noreferrerLinks: yes
Permalinks:
  posts: /:year/:filename/
menu:
  main:
    - name: Sobre mim
      url: /sobre
      weight: 1
    - name: Blog
      url: /posts/
      weight: 2
    - name: Contos
      url: /contos/
      weight: 3
    - name: Portfolio
      url: /portfolio
      weight: 4
params:
  author: William Amorim
  avatar: /images/me/foto_perfil.jpg
  baidu_verification: ''
  bing_verification: ''
  cdn_url: ''
  dateFormatToUse: ''
  description: ''
  gitalk:
    clientId: ''
    clientSecret: ''
    owner: ''
    repo: ''
  gitment:
    clientId: ''
    clientSecret: ''
    owner: ''
    repo: ''
  google_verification: ''
  gravatar: {}
  home_mode: ''
  image:
    height: 600
    url: cover.png
    width: 800
  keywords: ''
  logo:
    height: 40
    url: logo.png
    width: 127
  pinterest_verification: ''
  publisher:
    logo:
      height: 40
      url: logo.png
      width: 127
    name: Fastbyte01
  share:
    Facebook: no
    Linkedin: yes
    Twitter: yes
    copyright: This work is licensed under a Creative Commons Attribution-NonCommercial
      4.0 International License.
  since: 2020
  social:
    GitHub: williamorim
    Linkedin: william-amorim-796798210
    Twitter: wamorim_
  socialShare: yes
  subtitle: William Amorim
  utterances:
    owner: ''
    repo: ''
  valine:
    appId: your appId
    appKey: your appKey
    avatar: mm
    enable: no
    language: en
    notify: no
    placeholder: your comments ...
    verify: no
    visitor: yes
  yandex_verification: ''
author:
  name: William Amorim
